extends: base.yaml

experiment:
  name: oracle_left_fixed256_rdq

data:
  manifest_dir: /home/jasoncui/datasets/MMAUD/rdq_uav_experiment/manifests_oracle_left_fixed256
  image_mode: oracle_left
  image_size: [256, 256]

train:
  batch_size: 16

evaluation:
  batch_size: 32
